title = "frinux.fr"
baseURL = 'https://frinux.fr/'
languageCode = 'fr-fr'
defaultContentLanguage = "fr"

theme = "hugo-blog-awesome"

enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[menu]
  [[menu.main]]
    pageRef = "/"
    name = 'Accueil'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef = "posts"
    name = 'Articles'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef = "about"
    name = 'A propos'
    url = '/about/'
    weight = 30

[params]
  sitename = "frinux.fr"
  defaultColor = "auto"
  description = "Mon blog personnel"
  mainSections = ['posts']
  toc = false
  tocOpen = false
  goToTop = true
  dateFormat = "2 January 2006"
  rssFeedDescription = "summary"

[params.author]
  # avatar = "avatar.jpg"  # Put your avatar in assets/ folder
  intro = "frinux"
  name = "Francois"
  description = "Développeur fullstack senior. Nantais. Je consacre mon activité pro à des sujets à impact"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/frinux"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/francoislequemener/"

[[params.socialIcons]]
  name = "Rss"
  url = "/index.xml"
